### ISSUE TITLE
listing 1 of 1 type error

### ISSUE THREAD

**Issue by Ij888** [ricardoalcocer/appc_book_code#1]
![error](https://cloud.githubusercontent.com/assets/2773674/6993384/4d2dc7e4-daea-11e4-83fc-e2502d85ba03.jpg)

what could be the problem? 
I added the following to the `index.js` file

```
var win = Ti.UI.createWindow({
    backgroundColor: "#ffC300"
});

var mySwitch = Ti.UI.createSwitch({value:true});

win.add(mySwitch);
win.open();
```

 but the error alert pops up still.
Thanks.

**Comment by ricardoalcocer** [comment]
The error refers to "createwindow", when it should be "createWindow".  Your code snippet is right though.  I just tried that code and its working for me.  Are you still having the problem?

**Comment by Ij888** [comment]
I still get the error message. After going through all the *.js files, I can't find any culprit "createwindow" method as I have the correct "createWindow" method in my index.js file.

**Comment by Ij888** [comment]
Okay, I now see why!! Tags must have their first letters capitalized. So the error alert message is gone and but I don't see the switch on my Android device or the iOS emulator.

**Comment by ricardoalcocer** [comment]
Could you share your project?  I'm confused because you're talking about tags, but the code you're showing is non-Alloy code.

**Comment by Ij888** [comment]
My apologies, I had come to that realization from your book. I have commented out the non-Alloy code and used exactly the content of Listing 1.2, but I am only getting the alloy splashscreen.

**Comment by ricardoalcocer** [comment]
No problem.  If Listing 1.1 works and 1.2 doesn't it may be because 1.2 requires to project to be an Alloy project.  You should start a new project and make sure you select Alloy in the project wizard.  The listings in this chapter were not really meant to be run, but rather to establish the comparisons of Classic vs Alloy.  The important detail to keep in mind is that the code in 1.1 needs to be run in a Classic project, and the one in 1.2 in an Alloy project.

Let me know if you need me to send you fully working projects for these two examples.

R

**Comment by Ij888** [comment]
I have now successfully recreated the listings in Chapter 1, both on an iOS emulator and an Android device. Thanks for your helpful responses.
